"""update pronounce column

Revision ID: 4b2d3a522689
Revises: 3266f59bdf19
Create Date: 2023-03-09 15:34:06.766459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b2d3a522689'
down_revision = '3266f59bdf19'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dictionary', sa.Column('pronounce', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dictionary', 'pronounce')
    # ### end Alembic commands ###
