"""init

Revision ID: f5532dd9eadd
Revises: 4b2d3a522689
Create Date: 2023-03-27 10:37:38.413098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5532dd9eadd'
down_revision = '4b2d3a522689'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
